<div class="">
    <div class="">
        <div class="" style="width:80%">
            <p>This link does not exist more. This may occur due to either you have confirmed your acceptance already or you haven't given your response within the given time-frame.</p>
            <div class="buttons-set border-top-none">
                <button class="button align-left" onclick="redirectURL()" title="My Account"><span><span>My Account</span></span></button>
            </div>
        </div>
    </div>
</div>
<script>
    function redirectURL() {
        window.location.href = "<?php echo Mage::getBaseUrl().'customer/account'; ?>";
    }
</script>
