<?php
$data = $this->getLoanOfferStatus();
?>
<div class="">
    <div class="" style="width:80%">
        <?php if (isset($data) && !empty($data)) {
            if (isset($data->application_status) && $data->application_status == "ACCEPTED") {
                ?>
                <div class="">
                    <p>Your application has been accepted, you will receive a confirmation email soon.</p>
                    <div class="buttons-set border-top-none">
                        <button class="button align-left" onclick="redirectURL()" title="My Account"><span><span>My Account</span></span></button>
                    </div>
                </div>
    <?php } else { ?>
                <div class="">
                    <p>We are sorry to inform you that your loan application cannot be processed further.</p>
                    <div class="buttons-set border-top-none">
                        <button class="button align-left" onclick="redirectURL()" title="My Account"><span><span>My Account</span></span></button>
                    </div>
                </div>
    <?php }
} else { ?>
            <div class="buttons-set border-top-none">
                <button class="button align-left" onclick="redirectURL()" title="My Account"><span><span>My Account</span></span></button>
            </div>
<?php } ?>
    </div>
</div>
<script>
    function redirectURL() {
        window.location.href = "<?php echo Mage::getBaseUrl().'customer/account'; ?>";
    }
</script>
